# Generated by Django 2.0.1 on 2018-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='Book Name',
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Book Name'),
        ),
    ]
